In [12]:
import autograd
import autograd.numpy as np
import numpy as onp

In [18]:
degree = 5
coeffs = np.zeros(degree)
coeffs[degree - 1] = 1.0
x = onp.polynomial.hermite.hermroots(coeffs)


def foo(vec):
    return np.sum(onp.polynomial.hermite.hermval(vec[0] * x + vec[1], coeffs))

foo_grad = autograd.grad(foo)
foo_hess = autograd.hessian(foo)
foo_hess = autograd.hessian(foo)
foo_hvp = autograd.hessian_vector_product(foo)

x = np.array([2., 3.])
print(foo(x))
print(foo_grad(x))
print(foo_hess(x))
print(foo_hvp(x, x))



137176.0
[ 179936.   67072.]
[[ 176352.   64992.]
 [  64992.   24768.]]
[ 547680.  204288.]


In [21]:
x, w = onp.polynomial.hermite.hermgauss(5)
print(x)
print(y)

[-2.02018287 -0.95857246  0.          0.95857246  2.02018287]
[ 0.01995324  0.39361932  0.94530872  0.39361932  0.01995324]
