In [3]:
import feather
import json
import pandas as pd
import numpy as np

In [4]:
x = 5.0
y = [1., 2., 3.]

df = pd.DataFrame({'x': [5., 6.], 'z': [10., 11.]})
df_json = pd.DataFrame.to_json(df)

json_string = json.dumps({ 'x': x, 'y': y, 'df_json': df_json })
print json_string

{"y": [1.0, 2.0, 3.0], "x": 5.0, "df_json": "{\"x\":{\"0\":5.0,\"1\":6.0},\"z\":{\"0\":10.0,\"1\":11.0}}"}


In [24]:
# Use with json.R
json_filename = '/tmp/foo.json'
json_file = open(json_filename, 'r')
json_dat = json.load(json_file)
json_file.close()

print json_dat['a']
print json_dat['b']
# print json_dat['df'] # Not useful
print np.array(json_dat['mat'])
np.array(json_dat['mat'])[0, 2] # Seems to read it in correctly.

[0.6984, 0.6539, 0.5702, 0.9919, 0.6043]
[1]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


7

In [43]:
json_filename = '/tmp/foo_python.json'
json_file = open(json_filename, 'w')
mat = np.reshape(range(9), (3, 3))
vec = np.random.rand(10)
mat_list = mat.tolist()
vec_list = vec.tolist()
json_dat = json.dumps({'mat': mat_list, 'vec': vec_list})
json_file.write(json_dat)
json_file.close()

print mat


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [56]:
import os
analysis_name = 'simulated_data_small'
data_dir = os.path.join(os.environ['GIT_REPO_LOC'], 'LRVBLogitGLMM/LogitGLMMLRVB/inst/data/')
json_filename = os.path.join(data_dir, '%s_stan_dat.json' % analysis_name)
json_file = open(json_filename, 'r')
stan_dat = json.load(json_file)
json_file.close()

print stan_dat


{u'y_group': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 27, 27