In [3]:
import feather
import json
import pandas as pd
import numpy as np

In [4]:
x = 5.0
y = [1., 2., 3.]

df = pd.DataFrame({'x': [5., 6.], 'z': [10., 11.]})
df_json = pd.DataFrame.to_json(df)

json_string = json.dumps({ 'x': x, 'y': y, 'df_json': df_json })
print json_string

{"y": [1.0, 2.0, 3.0], "x": 5.0, "df_json": "{\"x\":{\"0\":5.0,\"1\":6.0},\"z\":{\"0\":10.0,\"1\":11.0}}"}


In [24]:
# Use with json.R
json_filename = '/tmp/foo.json'
json_file = open(json_filename, 'r')
json_dat = json.load(json_file)

print json_dat['a']
print json_dat['b']
# print json_dat['df'] # Not useful
print np.array(json_dat['mat'])
np.array(json_dat['mat'])[0, 2] # Seems to read it in correctly.

[0.6984, 0.6539, 0.5702, 0.9919, 0.6043]
[1]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


7

In [42]:
json_filename = '/tmp/foo_python.json'
json_file = open(json_filename, 'w')
mat = np.reshape(range(9), (3, 3))
vec = np.random.rand(10)
mat_list = mat.tolist()
vec_list = vec.tolist()
json_dat = json.dumps({'mat': mat_list, 'vec': vec_list})
json_file.write(json_dat)
json_file.close()

print mat


SyntaxError: invalid syntax (<ipython-input-42-f27c3c0f1ed2>, line 3)