In [2]:

import autograd.numpy as np

In [13]:
k = 5
const_k = 2

constraint_mat = np.random.random((const_k, k))

# Projection onto and perpindicular to the rows of x.
def make_projection_matrices(x):
    xx = np.matmul(x, x.T)
    proj_parallel = np.matmul(x.T, np.linalg.solve(xx, x))
    proj_perp = np.eye(x.shape[1]) - proj_parallel
    return proj_parallel, proj_perp

proj_parallel, proj_perp = make_projection_matrices(constraint_mat)
print(np.matmul(proj_parallel, constraint_mat.T) - constraint_mat.T) 
print(np.matmul(proj_perp, constraint_mat.T))



[[  0.00000000e+00   2.22044605e-16]
 [ -1.11022302e-15   8.88178420e-16]
 [ -5.55111512e-16   3.33066907e-16]
 [  1.80411242e-16  -8.32667268e-17]
 [  1.33226763e-15  -6.66133815e-16]]
[[ -4.53630496e-17  -1.87180097e-16]
 [  1.08355104e-15  -8.92898308e-16]
 [  4.67458997e-16  -2.54093419e-16]
 [ -1.67415497e-16   9.34549145e-17]
 [ -1.36925024e-15   7.17126978e-16]]


In [31]:
evals, evec = np.linalg.eigh(proj_perp)
keep_cols = np.abs(evals) > 1e-8
print(keep_cols)
assert(np.sum(keep_cols) == k - const_k)
proj_basis = evec[:, keep_cols]
print(proj_basis)
print(np.matmul(constraint_mat, proj_basis))

[False False  True  True  True]
[[ 0.2001649   0.92561634  0.        ]
 [-0.5660542  -0.07342726  0.1109886 ]
 [ 0.71562763 -0.3504077  -0.16908614]
 [-0.23901084  0.03145768 -0.9635188 ]
 [-0.26508031 -0.11860726  0.17527958]]
[[  2.07091328e-16   1.01323556e-16  -5.73177806e-17]
 [  2.00648442e-16   9.77637540e-17  -5.96295980e-17]]


array([[  2.07091328e-16,   1.01323556e-16,  -5.73177806e-17],
       [  2.00648442e-16,   9.77637540e-17,  -5.96295980e-17]])