In [1]:

import autograd.numpy as np

In [2]:
k = 5
const_k = 2

constraint_mat = np.random.random((const_k, k))

# Projection onto and perpindicular to the rows of x.
def make_projection_matrices(x):
    xx = np.matmul(x, x.T)
    proj_parallel = np.matmul(x.T, np.linalg.solve(xx, x))
    proj_perp = np.eye(x.shape[1]) - proj_parallel
    return proj_parallel, proj_perp

proj_parallel, proj_perp = make_projection_matrices(constraint_mat)
print(np.matmul(proj_parallel, constraint_mat.T) - constraint_mat.T) 
print(np.matmul(proj_perp, constraint_mat.T))



[[ -2.22044605e-16   2.22044605e-16]
 [ -1.11022302e-16  -3.33066907e-16]
 [ -1.11022302e-16   2.22044605e-16]
 [ -2.25514052e-17   3.33066907e-16]
 [ -1.11022302e-16  -2.22044605e-16]]
[[  1.60650308e-16  -2.18247677e-16]
 [  1.16007203e-16   2.93239123e-16]
 [  1.35980948e-16  -2.21419996e-16]
 [  2.21160500e-17  -3.39747772e-16]
 [  1.11536342e-16   1.97973297e-16]]


In [3]:
evals, evec = np.linalg.eigh(proj_perp)
keep_cols = np.abs(evals) > 1e-8
print(keep_cols)
assert(np.sum(keep_cols) == k - const_k)
proj_basis = evec[:, keep_cols]
print(proj_basis)
print(np.matmul(constraint_mat, proj_basis))

[False False  True  True  True]
[[ 0.39080477  0.61195798  0.02580819]
 [-0.57342487  0.33774402 -0.17998247]
 [-0.3946543  -0.37768697  0.64308703]
 [-0.32270145 -0.2611027  -0.7214113 ]
 [ 0.50849514 -0.54828309 -0.18150775]]
[[  3.25294577e-17   1.56347069e-16  -4.13729665e-16]
 [  1.12319992e-16   2.35106223e-16  -2.29809603e-16]]
