In [1]:
import trlib
# import autograd.numpy as np
# from autograd import grad, hessian, hessian_vector_product

In [3]:
import scipy.sparse
import numpy as np
from scipy.sparse.linalg import LinearOperator

H = scipy.sparse.diags(np.linspace(-1.0, 100.0, 1000),0)
g = np.ones(1000)
x, TR = trlib.trlib_solve(H, g, 1.0)
np.linalg.norm(x)
1.0000000000000002
x, TR = trlib.trlib_solve(H, g, .5, reentry=True, TR=TR)
0.50000000000000011

H_lo = LinearOperator(H.shape, matvec=lambda vec: H * vec)
x, TR = trlib.trlib_solve(H_lo, g, 1.0)
np.linalg.norm(x)


1.0000000000000004

In [10]:
h = np.random.random((5, 5))
h = np.matmul(h, h.transpose()) + np.eye(5)

def f(x):
    return 0.5 * np.dot(x, np.matmul(h, x))

def g(x):
    return np.matmul(h, x)

def hvp(x, g):
    return np.matmul(h, g)

trlib.umin(f, g, hvp, np.random.random(5))


it   obj         ‖g‖        radius     step       rho          ?  nhv
   0 +4.4772e+00 8.2341e+00 4.4721e-01 4.4721e-01 +1.0000e+00  +    1
   1 +1.5687e+00 4.7778e+00 8.9443e-01 6.2189e-01 +1.0000e+00  +    1
   2 +8.3092e-02 4.7673e-01 1.7889e+00 3.4147e-01 +1.0000e+00  +    2
   3 +2.3281e-03 9.3241e-02 3.5777e+00 5.5340e-02 +1.0000e+00  +    3
   4 +1.0250e-06 1.6006e-03 7.1554e+00 1.2866e-03 +1.0000e+00  +    4
   5 +1.9722e-14 1.9997e-07


array([  9.57325040e-08,  -1.05325259e-07,   5.31485231e-08,
        -1.23588008e-07,   2.34877964e-08])

In [15]:
import autograd
import autograd.numpy as np


def f(x):
    return 0.5 * np.dot(x, np.matmul(h, x))

g = autograd.grad(f)
hvp = autograd.hessian_vector_product(f)

trlib.umin(f, g, hvp, np.random.random(5))


it   obj         ‖g‖        radius     step       rho          ?  nhv
   0 +2.7673e+00 6.5189e+00 4.4721e-01 4.4721e-01 +1.0000e+00  +    1
   1 +6.2800e-01 3.0519e+00 8.9443e-01 3.9558e-01 +1.0000e+00  +    1
   2 +2.4369e-02 2.4871e-01 1.7889e+00 1.9172e-01 +1.0000e+00  +    2
   3 +6.6650e-04 4.9853e-02 3.5777e+00 3.0320e-02 +1.0000e+00  +    3
   4 +2.4716e-09 7.2302e-05 7.1554e+00 6.8655e-05 +1.0000e+00  +    5
   5 +5.8903e-41 2.2313e-20


array([ -1.69406589e-21,   6.77626358e-21,   0.00000000e+00,
         0.00000000e+00,   1.69406589e-21])

In [18]:
class objective(object):
    def __init__(self):
#         h = np.random.random((5, 5))
#         h = np.matmul(h, h.transpose()) + np.eye(5)
#         self.h = h
        pass
    def f(self, x):
        return f(x)
    
    def g(self, x):
        return g(x)
    
    def hvp(self, x, g):
        return hvp(x, g)
    
obj = objective()

trlib.umin(obj.f, obj.g, obj.hvp, np.random.random(5))


it   obj         ‖g‖        radius     step       rho          ?  nhv
   0 +4.3376e+00 7.9066e+00 4.4721e-01 4.4721e-01 +1.0000e+00  +    1
   1 +1.5664e+00 4.5036e+00 8.9443e-01 6.0426e-01 +1.0000e+00  +    1
   2 +2.0569e-01 8.2107e-01 1.7889e+00 4.8211e-01 +1.0000e+00  +    2
   3 +1.1983e-02 1.8182e-01 3.5777e+00 1.4201e-01 +1.0000e+00  +    3
   4 +6.1252e-06 3.9486e-03 7.1554e+00 3.1142e-03 +1.0000e+00  +    4
   5 +1.9048e-14 1.9660e-07


array([  1.08019418e-07,  -1.02545885e-07,   4.42319289e-08,
        -1.15797288e-07,   5.77872703e-10])