In [1]:
from VariationalBayes import ScalarParam, ModelParamsDict, VectorParam
from VariationalBayes.NormalParams import MVNParam, UVNParam, UVNParamVector
from VariationalBayes.GammaParams import GammaParam

# import math

from autograd import grad, hessian, jacobian, hessian_vector_product
import autograd.numpy as np
import autograd.numpy.random as npr
import autograd.scipy as asp
import scipy as sp

import copy
from scipy import optimize


In [13]:
# Load data saved by stan_results_to_json.R and run_stan.R in LRVBLogitGLMM.
import os
import json

analysis_name = 'simulated_data_small'
data_dir = os.path.join(os.environ['GIT_REPO_LOC'], 'LRVBLogitGLMM/LogitGLMMLRVB/inst/data/')
json_filename = os.path.join(data_dir, '%s_stan_dat.json' % analysis_name)
json_file = open(json_filename, 'r')
stan_dat = json.load(json_file)
json_file.close()

print stan_dat.keys()
K = stan_dat['K'][0]
NObs = stan_dat['N'][0]
NG = stan_dat['NG'][0]
N = NObs / NG
y_g_vec = np.array(stan_dat['y_group'])
y_vec = np.array(stan_dat['y'])
x_mat = np.array(stan_dat['x'])

[u'y_group', u'mu_prior_var', u'mu_prior_t', u'mu_prior_var_c', u'K', u'beta_prior_var', u'tau_prior_beta', u'N', u'mu_prior_mean_c', u'mu_prior_epsilon', u'mu_prior_mean', u'y', u'x', u'NG', u'beta_prior_mean', u'tau_prior_alpha']
[[ 1.0266  0.9278 -0.3675  1.4361 -0.1547]
 [ 0.0522 -0.2816 -0.0919  0.1045  0.0609]
 [-0.2987 -0.2145 -0.5899 -0.6017 -1.3334]
 ..., 
 [-1.3141 -2.0781 -1.7383 -1.4381 -1.7805]
 [ 0.352   1.0454 -0.4264 -0.5992  0.8535]
 [-0.6908  0.4598  0.7275  1.5379  0.5351]]


In [33]:
# Define a class to contain prior parameters.
class PriorParams(object):
    pass

PriorParams.mu_prior_mean = stan_dat['mu_prior_mean'][0]
PriorParams.mu_prior_var = stan_dat['mu_prior_var'][0]

PriorParams.beta_prior_mean = np.array(stan_dat['beta_prior_mean'])
PriorParams.beta_prior_var = np.array(stan_dat['beta_prior_var'])

PriorParams.tau_prior_beta = stan_dat['tau_prior_beta'][0]
PriorParams.tau_prior_alpha = stan_dat['tau_prior_alpha'][0]


print PriorParams.beta_prior_mean

[0 0 0 0 0]


In [45]:
foo = np.reshape(range(9), (3, 3))
print np.diagonal(foo, offset=0, axis1=-1, axis2=-2)
print np.diagonal(foo, offset=0, axis1=0, axis2=1)

[0 4 8]
[0 4 8]


In [ ]:
# Simulate data instead of loading it
if False:
    N = 20     # observations per group
    K = 25      # dimension of regressors
    NG = 500      # number of groups

    # Generate data
    def Logistic(u):
        return np.exp(u) / (1 + np.exp(u))

    NObs = NG * N
    true_beta = np.random.rand(K) - 0.5
    true_mu = 0.2
    true_tau = 4.0
    true_u = np.random.normal(true_mu, 1 / np.sqrt(true_tau), NG)

    x_mat = np.random.random(K * NObs).reshape(NObs, K) - 0.5
    y_g_vec = [ g for g in range(NG) for n in range(N) ]
    true_rho = Logistic(np.matmul(x_mat, true_beta) + true_u[y_g_vec])
    y_vec = np.random.random(NObs) < true_rho


In [14]:
# Build an object to contain a variational approximation to a K-dimensional multivariate normal.
glmm_par = ModelParamsDict()

glmm_par.push_param(UVNParam('mu'))
glmm_par.push_param(GammaParam('tau'))
glmm_par.push_param(MVNParam('beta', K))
glmm_par.push_param(UVNParamVector('u', NG))

glmm_par['mu'].mean.set(0.1)
glmm_par['mu'].var.set(1.0)

glmm_par['tau'].shape.set(2.1)
glmm_par['tau'].rate.set(2.1)

glmm_par['beta'].mean.set(np.full(K, 0.))
glmm_par['beta'].cov.set(0.2 * np.eye(K))

glmm_par['u'].mean.set(np.full(NG, 0.))
glmm_par['u'].var.set(np.full(NG, 0.1))
    
print N * NG
print glmm_par

1000
ModelParamsList:
	mu:
mu_mean: 0.1
mu_var: 1.0
	tau:
tau_shape: 2.1
tau_rate: 2.1
	beta:
beta_mean:
[ 0.  0.  0.  0.  0.]
beta_cov:
[[ 0.2  0.   0.   0.   0. ]
 [ 0.   0.2  0.   0.   0. ]
 [ 0.   0.   0.2  0.   0. ]
 [ 0.   0.   0.   0.2  0. ]
 [ 0.   0.   0.   0.   0.2]]
	u:
u_mean:
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
u_var:
[ 0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1
  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1
  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1
  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0

In [15]:
def DataLogLikelihood(x_mat, y_vec, e_beta, e_beta_outer, e_u, var_u, std_draws):
    rho_mean = e_u + np.matmul(x_mat, e_beta)
    rho_sd = np.sqrt(var_u + np.einsum('nk,kj,nj->n', x_mat, e_beta_outer, x_mat))
    z = np.einsum('i,j->ij', rho_sd, std_draws) + np.expand_dims(rho_mean, 1)

    # The sum is over observations and draws, so dividing by the draws size
    # gives the sum of sample expectations over the draws.
    # log(1 - p) = log(1 / (1 + exp(u))) = -log(1 + exp(u))
    logit_term = -np.sum(np.log1p(np.exp(z))) / std_draws.size
    y_term = np.sum(y_vec * rho_mean)
    return y_term + logit_term


def RandomEffectLogLikelihood(e_u, var_u, e_mu, var_mu, e_tau, e_log_tau):
    return -0.5 * e_tau * np.sum((e_mu - e_u) ** 2 + var_mu + var_u) + \
           0.5 * e_log_tau * len(e_u)


def Elbo(y_vec, x_mat, y_g_vec, glmm_par_elbo, std_draws):
    e_beta = glmm_par_elbo['beta'].mean.get()
    cov_beta = glmm_par_elbo['beta'].cov.get()
    e_beta_outer = glmm_par_elbo['beta'].e_outer()
    
    e_u = glmm_par_elbo['u'].mean.get()
    var_u = glmm_par_elbo['u'].var.get()
    
    e_mu = glmm_par_elbo['mu'].mean.get()
    var_mu = glmm_par_elbo['mu'].var.get()
    
    e_tau = glmm_par_elbo['tau'].e()
    e_log_tau = glmm_par_elbo['tau'].e_log()

    ll = \
        DataLogLikelihood(x_mat, y_vec, e_beta, e_beta_outer,
                          e_u[y_g_vec], var_u[y_g_vec], std_draws) + \
        RandomEffectLogLikelihood(e_u, var_u, e_mu, var_mu, e_tau, e_log_tau)

    K = len(e_beta)
    beta_prior_info = 0.01 * np.eye(K)
    beta_prior_mean = np.full(K, 0.)
    e_log_prior = \
        MVNPrior(beta_prior_mean, beta_prior_info, e_beta, cov_beta) + \
        UVNPrior(0., 0.01, e_mu, var_mu) + \
        GammaPrior(2.1, 3.1, e_tau, e_log_tau)
        
    entropy = \
        UnivariateNormalEntropy(var_mu) + \
        MultivariateNormalEntropy(cov_beta) + \
        UnivariateNormalEntropy(var_u) + \
        GammaEntropy(glmm_par_elbo['tau'].shape.get(), glmm_par_elbo['tau'].rate.get())

    return ll + e_log_prior + entropy


class KLWrapper():
    def __init__(self, glmm_par, x_mat, y_vec, y_g_vec, num_draws):
        self.__glmm_par_ad = copy.deepcopy(glmm_par)
        self.x_mat = x_mat
        self.y_vec = y_vec
        self.y_g_vec = y_g_vec
        draw_spacing = 1 / float(num_draws + 1)
        target_quantiles = np.linspace(draw_spacing, 1 - draw_spacing, num_draws)
        self.std_draws = sp.stats.norm.ppf(target_quantiles)
    def Eval(self, free_par_vec, verbose=False):
        self.__glmm_par_ad.set_free(free_par_vec)
        kl = -Elbo(self.y_vec, self.x_mat, self.y_g_vec,
                   self.__glmm_par_ad, std_draws=self.std_draws)
        if verbose: print kl
            
        # TODO: this is returning an array when it should be a scalar.
        return kl
    
    # Return a posterior moment of interest as a function of
    # unconstrained parameters.  In this case it is a bit silly,
    # but in full generality posterior moments may be a complicated
    # function of moment parameters.
    def GetMoments(self, free_par_vec):
        self.__glmm_par_ad.set_free(free_par_vec)
        return self.__glmm_par_ad['beta'].mean.get()



In [16]:
kl_wrapper = KLWrapper(glmm_par, x_mat, y_vec, y_g_vec, 10)
KLGrad = grad(kl_wrapper.Eval)
KLHess = hessian(kl_wrapper.Eval)
MomentJacobian = jacobian(kl_wrapper.GetMoments)
KLHessVecProd = hessian_vector_product(kl_wrapper.Eval)  
free_par_vec = glmm_par.get_free()
kl_wrapper.Eval(free_par_vec)

array([ 932.54079576])

In [17]:
import timeit

time_num = 10

print 'Function time:'
print timeit.timeit(lambda: kl_wrapper.Eval(free_par_vec), number=time_num) / time_num

print 'Grad time:'
print timeit.timeit(lambda: KLGrad(free_par_vec), number=time_num) / time_num

print 'Hessian vector product time:'
print timeit.timeit(lambda: KLHessVecProd(free_par_vec, free_par_vec + 1), number=time_num) / time_num

# so slow
# print 'Hessian time:'
# print timeit.timeit(lambda: KLHess(free_par_vec), number=time_num) / time_num


Function time:
0.00209040641785
Grad time:
0.00862188339233
Hessian vector product time:
0.0166306972504


In [18]:
import time

init_par_vec = free_par_vec

# Optimize.
vb_time = time.time()
print 'Running BFGS'
vb_opt_bfgs = optimize.minimize(
    lambda par: kl_wrapper.Eval(par, verbose=True), init_par_vec,
    method='bfgs', jac=KLGrad, tol=1e-2)

init_par_vec = free_par_vec
print 'Running Newton Trust Region'
vb_opt = optimize.minimize(
    lambda par: kl_wrapper.Eval(par, verbose=True),
    vb_opt_bfgs.x, method='trust-ncg', jac=KLGrad, hessp=KLHessVecProd, options={'maxiter': 5000})

vb_time = time.time() - vb_time

glmm_par_opt = copy.deepcopy(glmm_par)
glmm_par_opt.set_free(vb_opt.x)
print 'Done.'

Running BFGS
[ 932.54079576]
[ 697.8179427]
[ 1151.68450581]
[ 654.32213575]
[ 586.38182855]
[ 565.78919076]
[ 545.89465189]
[ 568.28345224]
[ 538.65921226]
[ 531.01406411]
[ 551.22447624]
[ 529.49173244]
[ 526.79661475]
[ 521.79201663]
[ 512.66664719]
[ 506.37020346]
[ 506.96861039]
[ 503.98543066]
[ 499.98240931]
[ 493.08166582]
[ 489.6193131]
[ 484.30893812]
[ 474.505217]
[ 482.39526397]
[ 471.15904276]
[ 466.46139106]
[ 458.59100826]
[ 453.13821856]
[ 445.09963222]
[ 441.39582233]
[ 441.53881632]
[ 439.65540535]
[ 436.37893917]
[ 435.63275647]
[ 434.18614553]
[ 429.58659268]
[ 426.56226799]
[ 427.90216723]
[ 425.31895326]
[ 423.12990291]
[ 423.36663264]
[ 422.08379646]
[ 420.7488758]
[ 419.47063459]
[ 439.73672877]
[ 419.42668995]
[ 419.347366]
[ 419.24866627]
[ 419.10612583]
[ 419.21794698]
[ 419.07610771]
[ 419.03320084]
[ 418.98659949]
[ 419.03409459]
[ 418.97093191]
[ 418.94162145]
[ 418.89531222]
[ 418.81438355]
[ 418.6930396]
[ 418.69023783]
[ 418.63165974]
[ 418.53892235]
[ 

In [19]:
print vb_time / 60

0.037557053566


In [20]:
# Check the random effect estimates.  This requires simulated data.
from ggplot import *
import pandas as pd
%matplotlib inline

plot_df = pd.DataFrame({ 'opt': glmm_par_opt['u'].mean.get(), 'true': true_u })
ggplot(plot_df, aes(x='true', y='opt')) + geom_point() + geom_abline(slope=1, intercept=0)

NameError: name 'true_u' is not defined

In [22]:
# LRVB with conjugate gradient
from scipy.sparse.linalg import LinearOperator
import sys

# The we will actually compute Hess^1 * moment_jac.T, leading to perhaps confusing
# naming of "columns".  
moment_jac = MomentJacobian(vb_opt.x)
ObjHessVecProdLO = LinearOperator((vb_opt.x.size, vb_opt.x.size), lambda par: KLHessVecProd(vb_opt.x, par))
# print moment_jac.T.shape
# print ObjHessVecProdLO.shape
# cg_res, info = scipy.sparse.linalg.cg(ObjHessVecProdLO, moment_jac.T)

cg_time = timeit.timeit()
lrvb_term = np.full(moment_jac.T.shape, float('nan'))
for col in range(moment_jac.shape[0]):
    sys.stdout.write('.')
    sys.stdout.flush()
    cg_res, info = sp.sparse.linalg.cg(ObjHessVecProdLO, moment_jac[col, :])
    assert info == 0
    lrvb_term[:, col] = cg_res
cg_time = timeit.timeit() - cg_time

print 'all done dude'

.....all done dude


In [23]:
# Slow, but maybe faster than using CG.
hess_time = timeit.timeit()
kl_hess = KLHess(vb_opt.x)
hess_time =  timeit.timeit() - hess_time

In [24]:
print kl_hess[0,:,:].shape
print moment_jac.shape

beta_cov_hess = np.matmul(moment_jac, np.linalg.solve(kl_hess[0, :, :], moment_jac.T))
beta_cov = np.matmul(moment_jac, lrvb_term)
print np.diag(beta_cov)
print np.diag(beta_cov_hess)
print np.diag(glmm_par_opt['beta'].cov.get())

(224, 224)
(5, 224)
[ 0.01833327  0.01884971  0.02760428  0.02634218  0.03285991]
[ 0.01833327  0.01884971  0.02760428  0.02634218  0.03285991]
[ 0.03155264  0.02984462  0.03841135  0.03356363  0.03436673]
