In [1]:
import autograd.numpy as np
from autograd import grad, hessian, jacobian
import autograd.numpy.random as npr
import copy

In [2]:
def taylor_sine(x):  # Taylor approximation to sine function
    ans = currterm = x
    i = 0
    while np.abs(currterm) > 0.001:
        currterm = -currterm * x**2 / ((2 * i + 3) * (2 * i + 2))
        ans = ans + currterm
        i += 1
    return ans

grad_sine = grad(taylor_sine)
print "Gradient of sin(pi) is", grad_sine(np.pi)

Gradient of sin(pi) is -0.999899529704


In [3]:
# Check Hessian of a quadratic function.
D = 5
H = npr.randn(D, D)
def fun(x):
    return np.dot(np.dot(x, H),x)
hess = hessian(fun)
x = npr.randn(D)
hess(x) - (H + H.T)

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [4]:
fun = lambda x: np.array([x, x**2, x**3])
val = npr.randn()
fun_jac = jacobian(fun)
fun_jac(val)  - np.array([1., 2*val, 3*val**2])

array([ 0.,  0.,  0.])

In [5]:
x = float("inf")
x == float("inf")
vec = np.array([1, 2, 3])
vec.size
vec_free = np.empty_like(vec)
vec_free[0] = 5
print vec_free
print 2 - np.exp(vec)
all(vec < 100)
False and all(False)


[5 0 0]
[ -0.71828183  -5.3890561  -18.08553692]


False

In [6]:
def unconstrain_vector(vec, lb, ub):
    if not all(vec <= ub): raise ValueError('Elements larger than the upper bound')
    if not all(vec >= lb): raise ValueError('Elements smaller than the lower bound')
    return unconstrain(vec, lb, ub)

def unconstrain_scalar(val, lb, ub):
    if not val <= ub: raise ValueError('Value larger than the upper bound')
    if not val >= lb: raise ValueError('Value smaller than the lower bound')
    return unconstrain(val, lb, ub)

def unconstrain(vec, lb, ub):    
    if ub <= lb: raise ValueError('Upper bound must be greater than lower bound')
    if ub == float("inf"):
        if lb == -float("inf"):
            return copy.copy(vec)
        else:
            return np.log(vec - lb)
    else: # the upper bound is finite
        if lb == -float("inf"):
            return -1 * np.log(ub - vec)
        else:
            return np.log(vec - lb) - np.log(ub - vec)

def constrain(free_vec, lb, ub):
    if ub <= lb: raise ValueError('Upper bound must be greater than lower bound')
    if ub == float("inf"):
        if lb == -float("inf"):
            return copy.copy(free_vec)
        else:
            return np.exp(free_vec) + lb
    else: # the upper bound is finite
        if lb == -float("inf"):
            return ub - np.exp(-1 * free_vec)
        else:
            exp_vec = np.exp(free_vec) 
            return (ub - lb) * exp_vec / (1 + exp_vec) + lb

print constrain(unconstrain_vector(np.array([1., 2., 3.]), -1.0, 4.0), -1.0, 4.0)
print constrain(unconstrain_vector(np.array([1., 2., 3.]), -1.0, float("inf")), -1.0, float("inf"))
print constrain(unconstrain_vector(np.array([1., 2., 3.]), -1 * float("inf"), 4.0), -1 * float("inf"), 4.0)
print constrain(unconstrain_vector(np.array([1., 2., 3.]), -1 * float("inf"), float("inf")), -1 * float("inf"), float("inf"))



[ 1.  2.  3.]
[ 1.  2.  3.]
[ 1.  2.  3.]
[ 1.  2.  3.]


In [7]:
range(1, 10)

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:

class VectorParam(object):
    def __init__(self, name, size, lb=-float("inf"), ub=float("inf")):
        self.name = name
        self.__size = size
        self.__free_size = size
        self.__val = np.empty(size)
        if lb >= ub: raise ValueError('Upper bound must strictly exceed lower bound')
        self.__lb = lb
        self.__ub = ub
    def __str__(self):
        return self.name + ': ' + str(self.__val)
    def names(self):
        return [ self.name + '_' + str(k) for k in range(self.size()) ]
    def set(self, val):
        if val.size != self.size(): raise ValueError('Wrong size for vector ' + self.name)
        self.__val = val
    def get(self):
        return self.__val
    def set_free(self, free_val):
        if free_val.size != self.size(): raise ValueError('Wrong size for vector ' + self.name)
        self.set(constrain(free_val, self.__lb, self.__ub))
    def get_free(self):
        return unconstrain_vector(self.__val, self.__lb, self.__ub)
    def size(self):
        return self.__size
    def free_size(self):
        return self.__free_size

    
class ScalarParam(object):
    def __init__(self, name, lb=-float("inf"), ub=float("inf")):
        self.name = name
        if lb >= ub: raise ValueError('Upper bound must strictly exceed lower bound')
        self.__val = 0.5 * (ub + lb)
        self.__lb = lb
        self.__ub = ub
    def __str__(self):
        return self.name + ': ' + str(self.__val)
    def names(self):
        return [ self.name ]
    def set(self, val):
        self.__val = val
    def get(self):
        return self.__val
    def set_free(self, free_val):
        self.set(constrain(free_val, self.__lb, self.__ub))
    def get_free(self):
        return unconstrain_scalar(self.__val, self.__lb, self.__ub)
    def size(self):
        return 1
    def free_size(self):
        return 1


mu = VectorParam("mu", 3, lb=0, ub=10)
mu.set(np.array([1., 2., 3.]))
mu.get()
foo = mu.get_free()
mu.set_free(foo)
mu.get()

tau = ScalarParam('tau', lb=0, ub=float("inf"))
tau.set(5)
# print dir(tau)
tau.get_free()
print tau
print mu

tau: 5
mu: [ 1.  2.  3.]


In [87]:

a = np.matrix([[1, 0.1], [0.1, 1]])
print a
a_chol_orig = np.linalg.cholesky(a)
print a_chol_orig
print a_chol_orig * a_chol_orig.T - a


nrow, ncol = np.shape(a)

[[ 1.   0.1]
 [ 0.1  1. ]]
[[ 1.          0.        ]
 [ 0.1         0.99498744]]
[[ 0.  0.]
 [ 0.  0.]]


In [139]:
import math

# Uses 0-indexing.
def sym_index(row, col):
    if row <= col:
        return col * (col + 1) / 2 + row
    else:
        return row * (row + 1) / 2 + col
        

def vectorize_matrix(mat, ld=True):
    nrow, ncol = np.shape(mat)
    if nrow != ncol: raise ValueError('mat must be square')
    vec_size = nrow * (nrow + 1) / 2
    vec = np.empty(vec_size)
    for col in range(ncol):
        for row in range(col + 1):
            if ld:
                vec[sym_index(row, col)] = mat[col, row]                
            else:
                vec[sym_index(row, col)] = mat[row, col]
    return vec

def unvectorize_matrix(vec, ld_only=False):
    mat_size = int(0.5 * (math.sqrt(1 + 8 * vec.size) - 1))
    if mat_size * (mat_size + 1) / 2 != vec.size: raise ValueError('Vector is an impossible size')
    mat = np.matrix(np.zeros([ mat_size, mat_size ]))
    for row in range(mat_size):
        for col in range(row + 1):
            mat[row, col] = vec[sym_index(row, col)]
            if (not ld_only) and row != col:
                mat[col, row] = mat[row, col]
    return mat


def pack_posdef_matrix(mat):
    return vectorize_matrix(np.linalg.cholesky(mat), ld=True)

def unpack_posdef_matrix(free_vec):
    mat_chol = unvectorize_matrix(free_vec, ld_only=True)
    return mat_chol * mat_chol.T

a = np.matrix(np.random.rand(4, 4))
sigma_val = a * a.T + np.eye(4)

print sigma_val
# vec = vectorize_matrix(sigma_val)
# print vec
# print unvectorize_matrix(vec)

print '-------\n'
print np.linalg.cholesky(sigma_val)
print vectorize_matrix(np.linalg.cholesky(sigma_val), ld=True)
print unvectorize_matrix(vectorize_matrix(np.linalg.cholesky(sigma_val), ld=True), ld_only=True)

unpack_posdef_matrix(pack_posdef_matrix(sigma_val)) - sigma_val


[[ 2.16944864  1.22600951  1.1020446   0.64770511]
 [ 1.22600951  2.53642267  1.09570046  0.6387525 ]
 [ 1.1020446   1.09570046  2.61612275  0.86641019]
 [ 0.64770511  0.6387525   0.86641019  1.72430484]]
-------

[[ 1.47290483  0.          0.          0.        ]
 [ 0.83237524  1.3577828   0.          0.        ]
 [ 0.74821168  0.34829399  1.39104038  0.        ]
 [ 0.43974675  0.20085554  0.33602889  1.17374157]]
[ 1.47290483  0.83237524  1.3577828   0.74821168  0.34829399  1.39104038
  0.43974675  0.20085554  0.33602889  1.17374157]
[[ 1.47290483  0.          0.          0.        ]
 [ 0.83237524  1.3577828   0.          0.        ]
 [ 0.74821168  0.34829399  1.39104038  0.        ]
 [ 0.43974675  0.20085554  0.33602889  1.17374157]]


matrix([[  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          -1.11022302e-16],
        [  0.00000000e+00,  -4.44089210e-16,   0.00000000e+00,
           0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
           0.00000000e+00],
        [ -1.11022302e-16,   0.00000000e+00,   0.00000000e+00,
           0.00000000e+00]])

In [140]:
class PosDefMatrixParam(object):
    def __init__(self, name, size):
        self.name = name
        self.__size = size
        self.__vec_size = size * (size + 1) / 2
        self.__val = np.matrix(np.zeros([size, size]))
    def __str__(self):
        return self.name + ': ' + str(self.__val)
    def names(self):
        return [ self.name ]
    def set(self, val):
        nrow, ncol = np.shape(val)
        if nrow != self.__size or ncol != self.__size: raise ValueError('Matrix is a different size')
        self.__val = val
    def get(self):
        return self.__val
    def set_free(self, free_val):
        if free_val.size != self.__vec_size: raise ValueError('Free value is the wrong length')
        self.set(unpack_posdef_matrix(free_val))
    def get_free(self):
        return pack_posdef_matrix(self.__val)
    def size(self):
        return self.__size
    def free_size(self):
        return self.__vec_size


    
sigma = PosDefMatrixParam('sigma', 4)
sigma.set(sigma_val)
sigma_0 = PosDefMatrixParam('sigma0', 4)
sigma_0.set_free(sigma.get_free())
print sigma_0.get() - sigma.get()

[[ 2.16944864  1.22600951  1.1020446   0.64770511]
 [ 1.22600951  2.53642267  1.09570046  0.6387525 ]
 [ 1.1020446   1.09570046  2.61612275  0.86641019]
 [ 0.64770511  0.6387525   0.86641019  1.72430484]]
[[ 2.16944864  1.22600951  1.1020446   0.64770511]
 [ 1.22600951  2.53642267  1.09570046  0.6387525 ]
 [ 1.1020446   1.09570046  2.61612275  0.86641019]
 [ 0.64770511  0.6387525   0.86641019  1.72430484]]


In [9]:
class ModelParamsList(object):
    def __init__(self):
        self.param_list = []
        self.__size = 0
        self.__free_size = 0
    def __str__(self):
        return 'ModelParamsList:\n' + '\n'.join([ '\t' + str(param) for param in self.param_list ])
    def push_param(self, param):
        self.param_list.append(param)
        self.__size = self.__size + param.size()
        self.__free_size = self.__free_size + param.size()
    def set(self, vec):
        if vec.size != self.__size: raise ValueError("Wrong size.")
        offset = 0
        for param in self.param_list:
            param.set(vec[offset:(offset + param.size())])
            offset = offset + param.size()
    def get(self):
        vec = np.empty(self.size())
        offset = 0
        for param in self.param_list:
            vec[offset:(offset + param.size())] = param.get()
            offset = offset + param.size()
        return vec
    def set_free(self, vec):
        if vec.size != self.__free_size: raise ValueError("Wrong size.")
        offset = 0
        for param in self.param_list:
            param.set_free(vec[offset:(offset + param.free_size())])
            offset = offset + param.free_size()
    def get_free(self):
        vec = np.empty(self.free_size())
        offset = 0
        for param in self.param_list:
            vec[offset:(offset + param.free_size())] = param.get_free()
            offset = offset + param.free_size()
        return vec
    def names(self):
        return np.concatenate([ param.names() for param in self.param_list])
    def size(self):
        return self.__size
    def free_size(self):
        return self.__free_size

par = ModelParamsList()
par.push_param(VectorParam("mu", 3))        
par.push_param(VectorParam("sigma", 3, lb=0))        
par.push_param(ScalarParam("tau", lb=0, ub=1))        


par.param_list[0].set(np.array([-10, 20, -30]))
par.param_list[1].set(np.array([1, 2, 3]))
par.param_list[2].set(0.5)

print par.param_list[2].get()


print par.names()
print par.get()
print par.get_free()

print par


0.5
['mu_0' 'mu_1' 'mu_2' 'sigma_0' 'sigma_1' 'sigma_2' 'tau']
[-10.   20.  -30.    1.    2.    3.    0.5]
[-10.          20.         -30.           0.           0.69314718
   1.09861229   0.        ]
ModelParamsList:
	mu: [-10  20 -30]
	sigma: [1 2 3]
	tau: 0.5


In [10]:
class ModelParamsDict(object):
    def __init__(self):
        self.param_dict = {}
        self.__size = 0
        self.__free_size = 0
    def __str__(self):
        return 'ModelParamsList:\n' + '\n'.join([ '\t' + str(param) for param in self.param_dict.values() ])
    def __getitem__(self, key):
        return self.param_dict[key]
    def push_param(self, param):
        self.param_dict[param.name] = param
        self.__size = self.__size + param.size()
        self.__free_size = self.__free_size + param.size()
    def set(self, vec):
        if vec.size != self.__size: raise ValueError("Wrong size.")
        offset = 0
        for param in self.param_dict.values():
            param.set(vec[offset:(offset + param.size())])
            offset = offset + param.size()
    def get(self):
        vec = np.empty(self.size())
        offset = 0
        for param in self.param_dict.values():
            vec[offset:(offset + param.size())] = param.get()
            offset = offset + param.size()
        return vec
    def set_free(self, vec):
        if vec.size != self.__free_size: raise ValueError("Wrong size.")
        offset = 0
        for param in self.param_dict.values():
            param.set_free(vec[offset:(offset + param.free_size())])
            offset = offset + param.free_size()
    def get_free(self):
        vec = np.empty(self.free_size())
        offset = 0
        for param in self.param_dict.values():
            vec[offset:(offset + param.free_size())] = param.get_free()
            offset = offset + param.free_size()
        return vec
    def names(self):
        return np.concatenate([ param.names() for param in self.param_dict.values()])
    def size(self):
        return self.__size
    def free_size(self):
        return self.__free_size

par = ModelParamsDict()
par.push_param(VectorParam("mu", 3))        
par.push_param(VectorParam("sigma", 3, lb=0))        
par.push_param(ScalarParam("tau", lb=0, ub=1))        


par.param_dict['mu'].set(np.array([-10, 20, -30]))
par.param_dict['sigma'].set(np.array([1, 2, 3]))
par.param_dict['tau'].set(0.5)

print par['tau'].get()


print par.names()
print par.get()
print par.get_free()

print par
print par['mu']

0.5
['mu_0' 'mu_1' 'mu_2' 'tau' 'sigma_0' 'sigma_1' 'sigma_2']
[-10.   20.  -30.    0.5   1.    2.    3. ]
[-10.          20.         -30.           0.           0.           0.69314718
   1.09861229]
ModelParamsList:
	mu: [-10  20 -30]
	tau: 0.5
	sigma: [1 2 3]
mu: [-10  20 -30]


In [11]:
np.concatenate((np.array([1,2]), np.array([3,4]), [5]), axis=0)
foo = [1, 2, 3, 4]
offset = 1
print foo[offset:(offset + 1)]
print foo[0:3]

foo = {}
foo['yues'] = 5
foo['blue'] = ScalarParam("mu")
print foo

for k, v in foo.iteritems():
    print k
    print v
    print '-------'
    
print foo.values()
    

[2]
[1, 2, 3]
{'blue': <__main__.ScalarParam object at 0x7fee652ae410>, 'yues': 5}
blue
mu: nan
-------
yues
5
-------
[<__main__.ScalarParam object at 0x7fee652ae410>, 5]
